apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: docker-gs-ping
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: docker-gs-ping
    app.kubernetes.io/part-of: docker-gs-ping
  name: docker-gs-ping
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: docker-gs-ping
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: docker-gs-ping
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/vbelouso-tenant/docker-gs-ping/docker-gs-ping@sha256:0b9e0eccf1aa026738cc215917edbb98c163f2fb7199d554d287ddf9ea3bb67e
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
