apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: docker-gs-ping
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: docker-gs-ping
    app.kubernetes.io/part-of: docker-gs-ping
  name: docker-gs-ping
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: docker-gs-ping
status:
  loadBalancer: {}
