apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: docker-gs-ping
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/vbelouso-tenant/docker-gs-ping/docker-gs-ping@sha256:0b9e0eccf1aa026738cc215917edbb98c163f2fb7199d554d287ddf9ea3bb67e
        name: container-image
        resources: {}
status: {}
